- test_typing_inspect.py
- typing_inspect.py
Fixes #17 
This adds support for upcoming Python 3.7. The `typing` module in this version was thoroughly reworked, but I tried to keep semantics as much close to the previous versions as possible.
> Support Python 3.7

- README.md
- requirements.txt
- test-requirements.txt
- test_typing_inspect.py
- typing_inspect.py
Fixes #19 
Unfortunately, the current API doesn't allow reliably infer whether a given key is required or not.
> Add (very) simple support for TypedDict keys

- setup.py
Python version constraints *must* be specified as environment markers.
Runtime setup.py checks will not be reflected in the metadata, resulting
in incorrect hard dependency on typing in dist-info and in wheels.
> Use environment marker for typing dependency instead of runtime

- LICENSE
- MANIFEST.in
Issue presented itself when I was packaging this for `conda-forge`. MIT License's terms require it's notice to be present in every copy of the Software. Since the `setup.py` indicates this is under MIT, this file should be here, and should also be packaged.
> Add MIT license (since MIT requires it's notice to be present).

- test_typing_inspect.py
- typing_inspect.py
Hello, I've been using `typing_inspect` for a while now and I just came across this little bug.
In the branch starting with `elif is_callable_type(arg[0]):` on line 288, the args to Callable aren't recursively evaluated. This PR adds the appropriate recursion and a test case for it.
Without recursing here, the following code
```
from typing_inspect import get_args
from typing import Union, Callable, Tuple
t = Union[str, Callable[[Tuple[int, ...]], int]]
try:
print(get_args(t, evaluate=True))
except Exception as e:
print("get_args({}, evaluate=True) -> {}".format(t, e))
```
Produces this output:
```
get_args(typing.Union[str, typing.Callable[[typing.Tuple[int, ...]], int]], evaluate=True) -> Callable[[arg, ...], result]: each arg must be a type. Got (typing.Tuple, <class 'int'>, Ellipsis). …
```
> made _eval_args recurse for args that are Callables

- requirements.txt
- setup.py
- test-requirements.txt
- test_typing_inspect.py
- typing_inspect.py
Adds an `is_literal_type` API, and fixes `get_args` for literal types on 3.6 and 2.7 (provided by `typing_extensions`).
[This feature is in 3.8](https://www.python.org/dev/peps/pep-0586/), but it's available as a backport to 3.7 and below as part of [`typing_extensions`](https://github.com/python/typing/tree/master/typing_extensions), so this adds `typing_extensions` as a dependency.
I've tested this pull request by running the unit tests against Python 2.7, 3.6, and 3.7.
> Support Literal (PEP 586)

- test_typing_inspect.py
- typing_inspect.py
In 3.7, `get_args(ClassVar)` (no parameter specified) would return an empty tuple. In 3.6 it would return `(None,)` because `__type__` is `None` in that case.
This copies the logic that already existed in `get_last_args` to normalize that case to an empty tuple.
I've tested this pull request by running the unit tests against Python 2.7, 3.6, and 3.7.
> Fix get_args for unparameterized ClassVar on <3.7

- typing_inspect.py
With introduction of Python 3.8 `get_args` `ValueError` message omits mentioning that `evaluate` can be `True` for `Python >= (3, 7, 0)` as derived from `NEW_TYPING` const.
> Account for Py 3.8 in "get_args" ValueError

- .travis.yml
Python 3.8 is present for a while now. Use stable release.
> Change 3.8-dev to 3.8

- .gitignore
- test_typing_inspect.py
- typing_inspect.py
- Adds function ``is_forward_ref`` which tests if ``tp`` is a :class:`typing.ForwardRef`.
- Adds function ``get_forward_arg`` which returns the string representation of the forward reference.
> Adding function `is_forward_ref`

- README.md
- test_typing_inspect.py
- typing_inspect.py
This PR adds an `is_final_type` function and extends `get_args` to support `Final` type. Supported Python versions are 2.7 and 3.6+ (via `typing_extensions` before 3.8).
Closes #61.
> Support Final (PEP 591)

- typing_inspect.py
Another take at #66 which keeps compatibility with older Python versions.
Fixes #60
> Handle Python 3.9 _SpecialGenericAlias

- typing_inspect.py
`typing_extensions` just re-exports `typing` in Python3.9. `type(typing.TypedDict)` is just a function in Python3.9, just as in `typing_extensions`.
Fixes #65
> import typing._TypedDictMeta in Python 3.9

- .travis.yml
- test_typing_inspect.py
- typing_inspect.py
This also fixes a minor `TypedDict` glitch and adds some basic testing.
Closes #65
> Try adding basic support for builtin geenrics

- test_typing_inspect.py
- typing_inspect.py
> Correctly support special aliases on Python 3.9

- requirements.txt
I think we need at least 3.7.4.2 these days.
Under 3.4.7.1, I get this error during import:
```
File ".../typing_inspect.py", line 17, in <module>
from typing_extensions import _TypedDictMeta as _TypedDictMeta_TE
ImportError: cannot import name '_TypedDictMeta' from 'typing_extensions' 
```
> Require newer typing-extensions

- test_typing_inspect.py
- typing_inspect.py
Hi 👋
This PR adds support for PEP 604 unions, that is unions that yield a `types.UnionType` object.
> Support PEP 604 unions, types.UnionType

- test-requirements.txt
Everything actually works just fine, it's just that the latest pathlib2
release dropped support for Python 3.5.{0,1} without indicating it in
their metadata...
See https://github.com/ilevkivskyi/typing_inspect/pull/80#issuecomment-1144743173.
> Fix tests suite on Python 3.5.{0,1}.

- test_typing_inspect.py
- typing_inspect.py
See https://github.com/ilevkivskyi/typing_inspect/pull/39#issuecomment-907637313.
> Make `get_origin(Literal[...]) == Literal`.

- test_typing_inspect.py
- typing_inspect.py
Added support for Python 3.10 UnionType (`int | str`) to `get_args` function
> Add support for UnionType in get_args

- test_typing_inspect.py
- typing_inspect.py
Closes #93 
This prevents `get_parameters` throwing an exception on python >= 3.9. 
This does lead to a difference in behaviour between different python versions, but the new class based alias introduced in 3.9 doesn't store the required info. So to maintaining the same behaviour would require a dictionary of the generic types to the correct output.
Example of change in behaviour:
**python <=3.8**
```
>>> from typing import List
>>> from typing_inspect import get_parameters
>>> get_parameters(List)
(~T,)
```
**python >=3.9**
```
>>> from typing import List
>>> from typing_inspect import get_parameters
>>> get_parameters(List)
()
```
> Handle non-indexed generics >= py3.9

- test_typing_inspect.py
- typing_inspect.py
This fixes a test on Python 3.14 because there Union[] also creates instances
of types.UnionType.
> Support types.UnionType in get_parameters()
